### ISSUE TITLE
 if results["IsErroredOnProcessing"]: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-ocrspace-addon#1]
Error on run

**Comment by mitchelljkotler** [comment]
I don't think returning a string was in the documentation, so I assume something is going wrong.  Can you add some more logging so you can see what it is returning and if their is an error message?  Then handle appropriately, whether that is exiting or retrying.

**Comment by duckduckgrayduck** [comment]
@mitchelljkotler Figured out the issue- "key" is referenced, but the secret is never declared in the workflow: https://github.com/MuckRock/documentcloud-ocrspace-addon/blob/main/.github/workflows/run-addon.yml
I can't make a PR as I don't know what you named the secret in your secrets

**Comment by duckduckgrayduck** [comment]
We are getting the TypeError because response is giving us a single string, not a dictionary response - "API Key is not specified. Please provide a valid API key."
